AllCops:
  RunRailsCops: false
  Exclude:
    - 'ruby/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/cassettes/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'lib/**/*'
    - 'db/migrate/*.rb'
    - 'db/schema.rb'

Lint/Void:
  Exclude: ['**/*_spec.rb']

# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 2
Lint/HandleExceptions:
  Enabled: true

# Offense count: 1
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Lint/SpaceBeforeFirstArg:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
Lint/StringConversionInInterpolation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: true

# Offense count: 3
Lint/UselessAssignment:
  Enabled: true

# Offense count: 2
Metrics/AbcSize:
  Max: 18

# Offense count: 36
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 110

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AccessModifierIndentation:
  Enabled: false

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/CommentIndentation:
  Enabled: false

# Offense count: 18
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/EachWithObject:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: true

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: true

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: true

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: false

# Offense count: 1
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
Style/IndentationConsistency:
  Enabled: true

# Offense count: 61
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: true

# Offense count: 6
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: true

# Offense count: 4
# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/SpaceAfterColon:
  Enabled: true

# Offense count: 4
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceAroundOperators:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: true

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: true

# Offense count: 6
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: true

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: true

# Offense count: 48
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: true

# Offense count: 8
# Cop supports --auto-correct.
Style/Tab:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: false
