mysqldb:
  image: busybox
  volumes:
    - /var/lib/mysql

mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - mysqldb

karajoker:
  build: .
  links:
    - mysql
  environment:
    RAILS_ENV: production
    DB_HOSTNAME: mysql
    DB_USERNAME: root
    DB_PASSWORD: root
    SECRET_KEY_BASE: a0e20b9d1c63e3666751294b5599d448e6fe7a1045b81d185c8f1a284cc9c6ec144efa96663b3cd101241695a664e7e4233840b2123a1fd41146c7b8210ad77b
  ports:
    - "80:80"
