#!/bin/bash
LIMIT=$1
FROM=$2
TO=$3
PORT=$4

function index() {
  LIMIT=$1
  YEARS=$2
  BODY="{\"limit\":\"$LIMIT\",\"years\":\"$YEARS\"}"

  echo "Index: $BODY"
  curl -H "Content-Type: application/json" -X POST -d "$BODY" http://localhost:$PORT/api/index
}

for (( YEAR=$FROM; YEAR<=$TO; YEAR++ ))
do
  index $LIMIT $YEAR
done
