FROM sjoerdmulder/graylog2
MAINTAINER Adrian Norberto Marino "adrianmarino@gmail.com"
#==============================================================================
#
#
#
#==============================================================================
# Linux
#==============================================================================
RUN cp /usr/share/zoneinfo/America/Argentina/Buenos_Aires /etc/localtime
