default: &default
  adapter: mysql2
  encoding: utf8
  pool: 20
  timeout: 5000
  host: <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] || 'root'  %>
  password: <%= ENV['DB_PASSWORD'] ||  '' %>

development:
  <<: *default
  database: karajoker_dev

test:
  <<: *default
  database: karajoker_test

production:
  <<: *default
  database: karajoker_prd
