default: &default
  adapter: mysql2
  encoding: utf8
  username: karajoker
  password: '29042902'
  host: localhost
  port: 3306
  pool: 20
  timeout: 5000

development:
  <<: *default
  database: karajoker_dev

test:
  <<: *default
  database: karajoker_test

production:
  <<: *default
  database: karajoker_prd