yourub_defaults: &yourub_defaults
  developer_key: 'AIzaSyCVU37P_YMZQ4nOc_oTDS9n3g-_wJqAsB4'
  youtube_api_service_name: 'youtube'
  youtube_api_version: 'v3'
  application_name: "karacas-200"
  application_version: "0.1"
  log_level: WARN

development:
  <<: *yourub_defaults

production:
  <<: *yourub_defaults

test:
  <<: *yourub_defaults
